/* Neural output and measured experiment artifacts only. Unicode offsets use code points. */
(() => {
  const names={context_pipeline:'上下文与位置增强流水线',pipeline:'实体 → 关系流水线',joint:'GPLinker 类型跨度变体',frozen_encoder:'冻结编码器消融'};
  const phases={waiting_for_baseline:'等待基线评测完成',not_prepared:'尚未准备',training:'模型训练中',validation_tuning:'验证集选阈值',test_evaluation:'独立测试评测',reporting:'汇总结果',completed:'评测已完成',failed:'运行失败'};
  let snapshot=null,result=null,detailId=null,busy=false,lastReport=null,runList=[],modelChosen=false,ieDatasets=[],ieEvaluationPending=false,ieInferencePending=false,ieDetailPending=false;
  const fmt=x=>Number.isFinite(x)?(x*100).toFixed(2)+'%':'—';
  const pp=x=>Number.isFinite(x)?(100*x).toFixed(2)+' pp':'—';
  const average=x=>x?`${fmt(x.mean)}${x.std===null?'':` ± ${(100*x.std).toFixed(2)} pp`}`:'—';
  const displayName=r=>(r.relation_features==='context_position'?names.context_pipeline:r.config.freeze_encoder?names.frozen_encoder:names[r.config.architecture])+' · seed '+r.config.seed;
  const empty=`<div class="ie-empty"><svg width="180" height="70" viewBox="0 0 180 70" aria-hidden="true"><path d="M42 35H138" stroke="#9db99f" stroke-width="2"/><circle cx="35" cy="35" r="24" fill="#e2ece4"/><circle cx="145" cy="35" r="24" fill="#e2ece4"/><text x="35" y="40" text-anchor="middle" fill="#24634d" font-size="12">实体</text><text x="145" y="40" text-anchor="middle" fill="#24634d" font-size="12">实体</text><text x="90" y="23" text-anchor="middle" fill="#687b74" font-size="11">关系</text></svg><p>输入一段中文，查看实体与关系。</p><small>结果来自本地训练模型，每个实体保留原文位置。</small></div>`;
  $('ie').innerHTML=`<div class="ie-grid"><div><div class="panel ie-editor"><div class="ie-kicker">CHINESE INFORMATION EXTRACTION</div><h2>把文本转为结构化信息</h2><form id="ieForm"><label for="ieModel">抽取模型</label><select id="ieModel"><option value="">正在读取训练结果…</option></select><p id="ieModelNote" class="caption"></p><label for="ieText">中文文本</label><textarea id="ieText" rows="7" maxlength="6000" required placeholder="例如：刘慈欣是《三体》的作者。">刘慈欣是《三体》的作者。</textarea><div class="row"><button id="ieExtract" type="submit">抽取实体与关系</button><button type="button" class="secondary" id="ieExample">填入示例</button></div></form><p class="caption">最多 6,000 字符 · 自动分窗 · 支持嵌套实体与重叠关系</p><div class="note">训练 schema 含作者、导演、主演、国籍、成立日期等 48 类关系（55 槽位）。可导入自有标注训练新 schema；分数尚未校准，点击实体或关系端点可定位原文。</div></div><details class="panel ie-training"><summary>训练一个独立模型</summary><form id="ieTrainForm"><label for="ieTrainDataset">信息抽取数据版本</label><select id="ieTrainDataset"></select><label>架构</label><select id="ieArchitecture"><option value="context_pipeline">上下文与位置增强流水线</option><option value="joint">GPLinker 类型跨度变体</option><option value="pipeline">实体识别 → 关系分类</option></select><div class="two"><div><label>训练轮数</label><input id="ieEpochs" type="number" min="1" max="30" value="6"></div><div><label>随机种子</label><input id="ieSeed" type="number" min="0" max="4294967295" value="42"></div></div><label><input id="ieFreeze" type="checkbox" style="width:auto"> 冻结编码器，仅训练抽取头</label><p class="caption">使用所选已清洗的数据版本。自有 schema 的抽取头会按类型和槽位重新初始化；新实验不进入冻结研究对照。</p><button id="ieTrainButton">开始微调</button></form></details></div><div class="panel"><div class="ie-subhead ie-result-head"><h2 style="margin:0">抽取结果</h2><button class="secondary" id="ieExport" disabled>导出 JSON</button></div><div id="ieOutput">${empty}</div></div></div>`;
  $('ie-eval').innerHTML=`<div class="ie-subhead"><div><div class="ie-kicker">FIXED PROTOCOL / REAL DATA</div><h2 style="margin:0">抽取质量、误差与模型代价</h2></div><div class="row"><span class="badge" id="iePhase">读取进度</span><button class="secondary" id="ieRefresh">刷新</button></div></div><div id="ieStudy"></div><div id="ieReport"></div><div id="ieAnalysis"></div><div class="panel hidden" id="ieDetail"></div>`;
  $('ie-methods').innerHTML=`<div class="ie-kicker">SOURCE REVIEW / DESIGN</div><h2>中文信息抽取的实现依据</h2><div class="ie-methods"><article><h3>PaddleNLP · DuIE</h3><p>固定 v2.8.1 版本，阅读 DuIE 任务说明。ERNIE token 多标签方案支持重叠 SPO，并提供官方复杂 object 的完整槽位评测。</p><p>本项目借鉴公开 schema 和数据清洗流程；使用 PyTorch 以适配当前环境。复杂 object 展开为二元槽位，指标与官方完整 SPO 不等价。</p><a target="_blank" rel="noopener" href="https://github.com/PaddlePaddle/PaddleNLP/tree/db99efd4dc99047922aae9842be66ab4538f93bf/examples/information_extraction/DuIE">固定代码版本 →</a></article><article><h3>GPLinker · 联合抽取</h3><p>阅读作者 DuIE v1 实现。用实体跨度、关系首部连接和尾部连接共同解码，支持嵌套与重叠关系。</p><p>本项目实现 Efficient GlobalPointer，并将实体跨度扩展为带类型的跨度。它是已有方法的工程实现与扩展，效果由公平对照检验。</p><a target="_blank" rel="noopener" href="https://github.com/bojone/GPLinker/blob/main/duie_v1.py">作者实现 →</a></article><article><h3>GPLinker PyTorch</h3><p>阅读固定提交 README，参考训练入口与 PyTorch 实验组织。旧脚本依赖数据目录和运行配置，需要补足字符位置、划分指纹及可查看的错误证据。</p><p>本项目补充验证选模、两种子统计、实体误差级联诊断、解码消融和 JSON 推理服务。</p><a target="_blank" rel="noopener" href="https://github.com/JunnYu/GPLinker_pytorch/tree/ff679b1e80a7adb0146d9ba66c9ddfe3107817a6">固定提交 →</a></article></div><div class="panel" style="margin-top:24px"><h3>从原文到结构化结果</h3><div class="ie-steps"><span>原文精确对齐</span>→<span>版本与划分审计</span>→<span>中文编码器微调</span>→<span>实体与关系解码</span>→<span>原文定位 + JSON</span></div><p>流水线与联合模型共享编码器、数据、训练轮数和优化器步数预算。阈值在验证集选择，测试集随后统一评测。默认模型按验证结果选架构、固定 seed 42 展示。</p><p>关系上下文增强：主客体跨度、实体间文本、实体两侧上下文及有向相对位置共同进入关系分类头。它针对语义角色混淆；使用两种子同预算对照检验收益。</p><div class="note">本轮在 4GB 显存上训练 BGE-small-zh 编码器，不是大语言模型。实体监督仅覆盖关系参与者；长原文过滤、首次提及对齐、有限 schema 及合成压力测试均是当前边界。</div><details><summary>数据版本与清洗审计</summary><div id="ieAudit" class="ie-data-audit"></div></details></div>`;
  $('ie-methods').insertAdjacentHTML('beforeend',`<div class="panel"><div class="ie-kicker">YOUR ANNOTATED DATA / SEPARATE VERSION</div><h3>导入自有实体与关系标注</h3><p class="muted">JSONL 使用 DuIE 风格的 text、spo_list，schema 定义关系和主客体类型。至少 20 条独立文本；来源清洗和划分通过后，可在抽取页独立微调。</p><details><summary>数据格式与负例约定</summary><pre class="log">${esc(JSON.stringify({text:'张三在甲公司任职。',spo_list:[{subject:'张三',subject_type:'人物',predicate:'任职',object:{'@value':'甲公司'},object_type:{'@value':'机构'}}]},null,2))}</pre><p class="caption">可逐行附 split=train / validation / test，必须全部指定。省略时固定 seed42 按文本 80/10/10 划分。显式空 spo_list 表示已标注无关系文本，未标注文本不能当负例；支持复杂 object 槽位。这里只按首次精确提及推导位置。</p></details><form id="ieImportForm"><div class="two"><div><label for="ieImportName">新数据版本名称</label><input id="ieImportName" pattern="[A-Za-z0-9_-]+" required placeholder="company-relations-v1"></div><div><label for="ieImportProvenance">来源与标注说明</label><input id="ieImportProvenance" placeholder="业务语料 / 标注范围 / 时间"></div></div><label for="ieSchemaJson">schema（JSON 数组）</label><textarea id="ieSchemaJson" rows="4" required>[{"predicate":"任职","subject_type":"人物","object_type":{"@value":"机构"}}]</textarea><label for="ieImportFile">本地 JSONL 文件（可选，最多 1MB）</label><input id="ieImportFile" type="file" accept=".jsonl,.txt"><label for="ieImportContent">已标注文本（每行一条 JSON）</label><textarea id="ieImportContent" rows="6" maxlength="1000000" required placeholder='{"text":"张三在甲公司任职。","spo_list":[...]}\n至少 20 条不同文本'></textarea><div class="note">不改写原文；无法对齐、过长及标注冲突记录隔离，跨划分重叠拒绝导入。训练必须覆盖所有 schema 槽位。自有版本不影响 DuIE2 研究产物。</div><button id="ieImportButton">清洗并建立数据版本</button></form><div id="ieImportResult"></div></div>`);
  $('ieImportFile').onchange=async()=>{const file=$('ieImportFile').files[0];if(!file)return;if(file.size>1000000){toast('文件不能超过 1MB');return;}$('ieImportContent').value=await file.text();};
  $('ieImportForm').onsubmit=async e=>{e.preventDefault();$('ieImportButton').disabled=true;try{const d=await api('/api/ie/datasets',{name:$('ieImportName').value,content:$('ieImportContent').value,schema_json:$('ieSchemaJson').value,provenance:$('ieImportProvenance').value||'user-provided'});await refreshIE();$('ieTrainDataset').value=d.id;$('ieImportResult').innerHTML=`<div class="note">已建立 ${esc(d.id)}：${Object.entries(d.counts).map(([split,c])=>`${split} ${c.documents}`).join(' / ')} 条，${d.schemas.length} 个槽位。去重/隔离统计：${esc(JSON.stringify(d.source_statistics))}。可回到抽取页选择该版本微调。</div>`;toast('自有关系标注已清洗并保存');}catch(e){toast(e.message);}finally{$('ieImportButton').disabled=false;}};
  function modelNote(){const r=runList.find(x=>x.id===$('ieModel').value);$('ieModelNote').textContent=r?`${r.id} · ${r.dataset} · ${r.status==='completed'?'已训练 checkpoint':'尚未完成'}${r.research_protocol?' · 冻结研究模型':''}${snapshot?.state.phase!=='completed'?' · 研究仍在运行，当前结果为预览':''}`:'请等待首个模型完成训练';}
  $('ieModel').onchange=()=>{modelChosen=true;modelNote();};
  $('ieExample').onclick=()=>{$('ieText').value='刘慈欣是《三体》的作者。';};
  function highlight(active=[]){
    const focus=new Set(active),chars=Array.from(result.text);let html='',last=null,part='';
    function flush(){if(!part)return;html+=last?`<mark class="${last.focus?'focus':''}" title="${esc(last.title)}">${esc(part)}</mark>`:esc(part);part='';}
    for(let i=0;i<chars.length;i++){
      const entities=result.entities.filter(e=>e.start<=i&&i<e.end),state=entities.length?{title:entities.map(e=>e.type+'：'+e.text).join(' / '),focus:entities.some(e=>focus.has(e.id))}:null;
      if(JSON.stringify(state)!==JSON.stringify(last)){flush();last=state;}part+=chars[i];
    }flush();$('ieAnnotated').innerHTML=html;
    document.querySelectorAll('[data-entity]').forEach(b=>b.classList.toggle('active',focus.has(b.dataset.entity)));
  }
  function drawResult(){
    const relations=result.relation_groups||result.relations;
    $('ieOutput').innerHTML=`<div class="ie-summary"><span><strong>${result.entities.length}</strong> 个实体</span><span><strong>${relations.length}</strong> 条关系</span><span class="badge">${result.windows} 个窗口</span></div><p class="caption">结果来源：${esc(names[result.model_architecture]||result.model_architecture)} · ${esc(result.run_id)} · 实体/关系 logit 阈值 ${result.thresholds.entity} / ${result.thresholds.relation}</p><div id="ieAnnotated" class="ie-highlight"></div><p class="ie-legend">绿色：预测实体 · 点击后以金色定位 · 相交跨度可有多个类型</p><div class="ie-chips">${result.entities.map(e=>`<button data-entity="${esc(e.id)}" title="字符 [${e.start}, ${e.end})">${esc(e.text)} <small> / ${esc(e.type)}</small></button>`).join('')}</div><h3>关系三元组</h3><p class="caption">相同类型、主客体表面字符串及关系槽位合并展示，原始提及链接保留在 JSON。</p>${relations.length?relations.map(r=>`<div class="ie-triple"><div class="ie-triple-flow"><button class="ie-node" data-entity="${esc(r.subject)}">${esc(r.subject_text)}<small>${esc(result.entities.find(e=>e.id===r.subject)?.type)}</small></button><div class="ie-edge">${esc(r.label)}<span>→</span></div><button class="ie-node" data-entity="${esc(r.object)}">${esc(r.object_text)}<small>${esc(result.entities.find(e=>e.id===r.object)?.type)}</small></button></div><p class="caption">抽取分数 ${fmt(r.confidence)} · 尚未校准${r.mention_links?.length>1?` · ${r.mention_links.length} 组原文提及链接`:""}</p></div>`).join(''):'<p class="muted">当前模型未发现超过阈值的已知关系。可查看实体结果，或尝试更明确的关系表达。</p>'}<p class="caption">${esc(result.limitations)}${result.candidate_limit_reached?' 本段触发候选数量上限。':''}</p><details><summary>查看完整结构化 JSON</summary><pre class="log ie-json">${esc(JSON.stringify(result,null,2))}</pre></details>`;
    highlight();document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>highlight([b.dataset.entity]));$('ieExport').disabled=false;
  }
  $('ieForm').onsubmit=async e=>{e.preventDefault();ieInferencePending=true;$('ieExtract').disabled=true;$('ieExtract').textContent='模型推理中…';try{result=await api('/api/ie/extract',{text:$('ieText').value,run_id:$('ieModel').value||null});drawResult();}catch(e){toast(e.message);}finally{ieInferencePending=false;$('ieExtract').disabled=!runList.some(x=>x.status==='completed');$('ieExtract').textContent='抽取实体与关系';}};
  $('ieExport').onclick=()=>{if(!result?.export_url)return;const a=document.createElement('a');a.href=result.export_url;a.download='information-extraction.json';document.body.append(a);a.click();a.remove();};
  $('ieTrainForm').onsubmit=async e=>{e.preventDefault();try{const run=await api('/api/ie/train',{dataset_id:$('ieTrainDataset').value,architecture:$('ieArchitecture').value,epochs:+$('ieEpochs').value,seed:+$('ieSeed').value,freeze_encoder:$('ieFreeze').checked});toast('实体与关系抽取模型训练已启动');await refreshIE();document.querySelector('[data-view="ie-eval"]').click();await showDetail(run.id);}catch(e){toast(e.message);}};
  function study(){
    const s=snapshot.state,d=snapshot.dataset;
    $('iePhase').textContent=phases[s.phase]||s.phase;
    if(!d){$('ieStudy').innerHTML='<p class="muted">请先准备 DuIE2 数据。</p>';return;}
    $('ieDataCount').textContent='10k / 2k / 4k';$('ieSchemaCount').textContent=d.schemas.length+' 种';$('ieRunCount').textContent=snapshot.experiments.filter(e=>e.status==='completed').length+' / '+snapshot.experiments.length;
    let html=`<div class="ie-cards"><article><small>训练 / 验证 / 测试 · 文本数</small><strong>${d.counts.train.documents.toLocaleString()} / ${d.counts.validation.documents.toLocaleString()} / ${d.counts.test.documents.toLocaleString()}</strong><small>固定来源与不重叠划分</small></article><article><small>结构化关系监督</small><strong>${d.counts.train.triples.toLocaleString()}</strong><small>${d.schemas.length} 个关系槽位 · ${d.entity_types.length} 种实体类型</small></article><article><small>研究配置</small><strong>3 方法 × 2 seeds</strong><small>另有 1 次冻结编码器消融 · 每次 6 epochs</small></article></div><div class="panel"><h3>固定协议实验</h3><div class="ie-table"><table><thead><tr><th>模型</th><th>状态</th><th>轮数进度</th><th>最佳验证关系 F1</th><th>峰值显存</th></tr></thead><tbody>${snapshot.experiments.map(e=>`<tr><td><button data-ie-run="${esc(e.run)}">${esc(names[e.name])} · seed ${e.seed}</button></td><td>${esc(status[e.status]||e.status)}</td><td>${e.epochs_completed||e.current_epoch||0} / ${e.config.epochs}${e.status==='running'&&e.batches_per_epoch?`<div class="ie-progress"><i style="width:${Math.min(100,100*e.batches_done/e.batches_per_epoch)}%"></i></div>`:''}</td><td>${fmt(e.best_validation_relation_f1)}</td><td>${e.peak_cuda_memory_mb?Math.round(e.peak_cuda_memory_mb)+' MB':'—'}</td></tr>`).join('')}</tbody></table></div><p class="caption">checkpoint 按验证关系 F1 选择；此处为零阈值的逐轮最佳值，最终阈值另由验证集选择。</p>${s.error?`<p class="error">${esc(s.error)}</p>`:''}${s.phase!=='completed'?`<p class="ie-pending">${esc(phases[s.phase]||s.phase)}。每组模型完成训练及验证阈值选择后统一评测测试集；上下文扩展协议在原组测试前固定。</p>`:''}</div>`;
    $('ieStudy').innerHTML=html;bindRuns();
    $('ieAudit').innerHTML=`<p>来源：<a href="https://github.com/PaddlePaddle/PaddleNLP/issues/447" target="_blank" rel="noopener">官方仓库数据下载讨论</a>。原始训练 171,293 条、dev 20,674 条；此轮测试来自固定 dev 子集。</p><pre class="log">${esc(JSON.stringify({dataset:d.id,counts:d.counts,source_audit:d.source_statistics,split_sha256:d.split_sha256,archive_sha256:d.archive_sha256},null,2))}</pre><ul>${d.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
  }
  function bindRuns(){document.querySelectorAll('[data-ie-run]').forEach(b=>b.onclick=()=>showDetail(b.dataset.ieRun).catch(e=>toast(e.message)));}
  function renderAnalysis(){const a=snapshot.analysis;if(!a)return;
    const labels={one_gold_slot:'单个金标槽位',multiple_gold_slots:'多个金标槽位',distinct_overlapping_spans:'不同边界跨度重叠',non_overlapping_spans:'跨度不重叠',all_typed_surfaces_seen_in_train:'带类型表面字符串均在 train 出现',some_typed_surface_unseen:'包含 train 未出现的带类型表面字符串',train_support_1_49:'关系训练支持 1–49',train_support_50_199:'关系训练支持 50–199',train_support_200_plus:'关系训练支持 ≥200',exclude_12_early_flow_smoke_rows:'排除早期流程自测 12 条'};
    $('ieAnalysis').innerHTML=`<div class="panel"><h3>难度分组 · 描述性分析</h3><div class="ie-table"><table><thead><tr><th>分组</th><th>文本 / 槽位数</th><th>流水线关系 F1</th><th>联合模型关系 F1</th><th>上下文增强 F1</th></tr></thead><tbody>${Object.entries(labels).map(([key,label])=>{const p=a.results.pipeline[key],j=a.results.joint[key];return `<tr><td>${esc(label)}</td><td>${p.documents??p.slots} ${p.documents===undefined?'槽位':'文本'}</td><td>${fmt(p.mean_relation_f1)}</td><td>${fmt(j.mean_relation_f1)}</td><td>${fmt(a.results.context_pipeline?.[key]?.mean_relation_f1)}</td></tr>`;}).join('')}</tbody></table></div><p class="caption">${esc(a.scope)}。分组同时有标签构成和文本难度差异，不能归因于单一因素；“未出现”不排除编码器预训练见过。</p><details><summary>流程自测与位置歧义披露</summary><p class="caption">${esc(a.flow_smoke_disclosure)}</p><p class="caption">派生位置存在重复提及的文档数：${esc(JSON.stringify(a.ambiguous_offset_documents))}。跨度取首次精确匹配，并非人工 NER 边界标注。</p></details></div>`;
  }
  function renderErrorCategories(){
    const values=snapshot.analysis?.error_categories;if(!values)return;
    $('ieAnalysis').insertAdjacentHTML('beforeend',`<div class="panel"><h3>实体遗漏与语义角色错误 · seed42</h3><div class="ie-table"><table><thead><tr><th>方法</th><th>双方实体已检出，关系遗漏</th><th>参与者表面 / 类型缺失</th><th>金标实体对上多报错误角色</th></tr></thead><tbody>${Object.entries(values).map(([name,v])=>`<tr><td>${esc(names[name])}</td><td>${v.counts.missing_despite_both_typed_surfaces_detected||0}</td><td>${v.counts.missing_with_participant_surface_or_type_absent||0}</td><td>${v.counts.extra_wrong_role_on_gold_typed_pair||0}</td></tr>`).join('')}</tbody></table></div><p class="caption">排除早期12条自测文本，统计剩余3,988条。前两列按遗漏关系划分；错角色列统计多报的关系。精确表面字符串与类型匹配，属于描述性分析，不是互斥的因果归因。</p><details><summary>常见同实体对角色误判</summary>${Object.entries(values).map(([name,v])=>`<p><strong>${esc(names[name])}</strong>：${v.role_confusions.slice(0,5).map(x=>`${esc(x.gold)} → ${esc(x.predicted)} (${x.count})`).join('；')||'未发现此类遗漏与多报共现'}</p>`).join('')}</details></div>`);
  }
  function renderReport(){
    const r=snapshot.report;if(!r)return;if(lastReport===(snapshot.context_report?.finished_at||r.finished_at))return;lastReport=snapshot.context_report?.finished_at||r.finished_at;
    const oracle=r.experiments.find(e=>e.name==='pipeline'&&e.seed===42).diagnostics.gold_entity_oracle;
    const noTail=r.experiments.find(e=>e.name==='joint'&&e.seed===42).diagnostics.no_tail_decode;
    $('ieReport').innerHTML=`<div class="panel"><h3>完整测试集 · 4,000 条文本</h3><div class="ie-table"><table><thead><tr><th>方法</th><th>关系 Micro-F1</th><th>实体 Micro-F1</th><th>前缀压力测试下降</th></tr></thead><tbody>${Object.entries(r.aggregates).map(([name,a])=>`<tr><td>${esc(names[name])}</td><td><strong>${average(a.relation_f1)}</strong></td><td>${average(a.entity_f1)}</td><td>${pp(a.stress_drop?.mean??(name==='context_pipeline'?snapshot.context_report.experiments.reduce((v,e)=>v+e.diagnostics.stress.drop_f1,0)/2:null))}</td></tr>`).join('')}</tbody></table></div><p class="caption">主模型报告 2 个种子的均值 ± 样本标准差；冻结编码器为 seed42 单次。实体只评关系参与者；关系按带类型的主客体表面字符串与槽位精确匹配。</p><div class="note">验证集选中：${esc(names[r.selected_architecture])}。默认部署使用该架构的 seed42 checkpoint，未按测试分数挑选种子。此分数不等于官方完整多槽 SPO 指标。</div><p>seed42 联合模型相对流水线关系 F1：<strong>${pp(r.paired_seed42.delta_relation_f1)}</strong>，文本配对 95% 区间 [${pp(r.paired_seed42.ci95[0])}, ${pp(r.paired_seed42.ci95[1])}]。</p>${snapshot.context_report?`<p>上下文增强 seed42 相对流水线：<strong>${pp(snapshot.context_report.paired_seed42.delta_relation_f1)}</strong>，95% 区间 [${pp(snapshot.context_report.paired_seed42.ci95[0])}, ${pp(snapshot.context_report.paired_seed42.ci95[1])}]。</p>`:''}<p class="caption">固定两个已训练模型，600 次文本 bootstrap；不包含训练种子总体不确定性，无多重比较校正。</p></div><div class="panel"><h3>误差诊断与消融</h3><div class="ie-cards"><article><small>流水线输入真实实体</small><strong>${fmt(oracle.relation.f1)}</strong><small>测试关系 F1 · 真实实体条件诊断，不能用于部署表现</small></article><article><small>取消尾部连接交集</small><strong>${fmt(noTail.relation.f1)}</strong><small>联合模型 seed42 · 同权重解码消融</small></article><article><small>冻结编码器</small><strong>${fmt(r.aggregates.frozen_encoder.relation_f1.mean)}</strong><small>同轮数独立训练 · seed42</small></article></div><p class="caption">压力测试固定抽取同组 1,000 条测试文本，前置“信息：”，平移所有实体字符位置，保留关系标签。它检验前缀敏感性，不能代表真实业务分布外泛化。</p></div>`;
  }
  async function showDetail(id){
    detailId=id;const d=await api('/api/ie/runs/'+encodeURIComponent(id));ieEvaluationPending=d.evaluation_status?.status==='running';ieDetailPending=['queued','running'].includes(d.status);const m=d.test_metrics||d.tuned_validation_metrics||d.validation_metrics;
    $('ieDetail').classList.remove('hidden');$('ieDetail').innerHTML=`<div class="ie-subhead"><div><div class="ie-kicker">EXPERIMENT DETAIL</div><h3 style="margin:0">${esc(displayName(d))}</h3></div><button id="ieUseModel" class="secondary" ${d.status==='completed'?'':'disabled'}>用此模型抽取</button></div><p class="caption">${esc(d.id)} · ${esc(status[d.status]||d.status)} · 最佳 epoch ${d.best_epoch||'—'}</p>${m?`<div class="metrics"><div><span class="muted">关系 Precision</span><strong>${fmt(m.relation.precision)}</strong></div><div><span class="muted">关系 Recall</span><strong>${fmt(m.relation.recall)}</strong></div><div><span class="muted">关系 F1</span><strong>${fmt(m.relation.f1)}</strong></div></div><p class="caption">${d.test_metrics?'独立测试集':'验证集'} · ${m.documents} 条文本 · 实体 F1 ${fmt(m.entity.f1)} · ${m.per_relation.length} 槽位 Macro-F1 ${fmt(m.macro_relation_f1)}</p>`:''}${d.status==='completed'&&!d.research_protocol?`<button id="ieEvaluateButton" class="secondary" ${ieEvaluationPending?'disabled':''}>${ieEvaluationPending?'独立测试评测中…':'评测独立测试集'}</button><p class="caption">CPU 评测所选数据版本的完整测试集，不参与 DuIE2 冻结研究。${esc(d.evaluation_status?.error||'')}</p>`:''}${ieChart(d.history||[])}${m?'<h3>逐关系槽位</h3><input id="ieSchemaSearch" class="ie-schema-filter" aria-label="筛选关系槽位" placeholder="筛选：作者 / 出生地 / 类型…"><div class="ie-table" id="ieSchemaTable"></div>':''}${d.test_errors?.length?`<details><summary>错误样本（展示前 ${d.test_errors.length} 条）</summary><div class="ie-errors">${d.test_errors.map(x=>`<article class="data-item"><p>${esc(x.text)}</p><small>${esc(x.source_file)}:${x.source_line}</small><pre class="log">${esc(JSON.stringify({遗漏:x.missing,多报:x.extra},null,2))}</pre></article>`).join('')}</div></details>`:''}<details style="margin-top:18px"><summary>配置与运行环境</summary><pre class="log">${esc(JSON.stringify({config:d.config,relation_features:d.relation_features,dataset_sha256:d.dataset_sha256,parameters:d.parameters,trainable_parameters:d.trainable_parameters,model_revision:d.model_revision,seconds:d.seconds,optimizer_steps:d.optimizer_steps,amp_skipped_updates:d.amp_skipped_updates,peak_cuda_memory_mb:d.peak_cuda_memory_mb,thresholds:d.thresholds,versions:d.versions},null,2))}</pre></details>`;
    if($('ieEvaluateButton'))$('ieEvaluateButton').onclick=async()=>{try{await api('/api/ie/runs/'+encodeURIComponent(id)+'/evaluate',{});toast('独立信息抽取测试已启动');await showDetail(id);}catch(e){toast(e.message);}};
    $('ieUseModel').onclick=()=>{$('ieModel').value=id;modelChosen=true;modelNote();document.querySelector('[data-view="ie"]').click();};
    if(m){function table(){const query=$('ieSchemaSearch').value.trim();const values=m.per_relation.filter(x=>[x.label,x.subject_type,x.object_type].some(v=>v.includes(query)));$('ieSchemaTable').innerHTML=`<table><thead><tr><th>关系槽位</th><th>主语 → 宾语类型</th><th>Precision</th><th>Recall</th><th>F1</th><th>真实条数</th></tr></thead><tbody>${values.map(x=>`<tr><td>${esc(x.label)}</td><td>${esc(x.subject_type)} → ${esc(x.object_type)}</td><td>${fmt(x.precision)}</td><td>${fmt(x.recall)}</td><td>${fmt(x.f1)}</td><td>${x.gold}</td></tr>`).join('')}</tbody></table>`;}$('ieSchemaSearch').oninput=table;table();}
  }
  function ieChart(history){if(!history.length)return '';const w=540,h=175,x=i=>42+i*450/Math.max(1,history.length-1),y=v=>140-115*v;return `<h3>逐轮验证 F1</h3><svg viewBox="0 0 ${w} ${h}" class="chart" role="img" aria-label="逐轮验证实体与关系 F1"><path d="M42 25V140H500" fill="none" stroke="#dce4df"/>${[0,.5,1].map(v=>`<text x="4" y="${y(v)+4}" font-size="10" fill="#687b74">${(100*v).toFixed(0)}%</text>`).join('')}${[['entity_f1','#97ac86'],['relation_f1','#24634d']].map(([k,color])=>`<polyline points="${history.map((v,i)=>x(i)+','+y(v[k])).join(' ')}" fill="none" stroke="${color}" stroke-width="2"/>`).join('')}${history.map((v,i)=>`<text x="${x(i)}" y="156" text-anchor="middle" font-size="10" fill="#687b74">${v.epoch}</text>`).join('')}</svg><p class="caption">横轴 epoch · 纵轴 F1（%）· 浅绿实体、深绿关系 · 验证集、零阈值</p>`;}
  async function refreshIE(){if(busy)return;busy=true;try{
    [snapshot,runList,ieDatasets]=await Promise.all([api('/api/ie'),api('/api/ie/runs'),api('/api/ie/datasets')]);const oldDataset=$('ieTrainDataset').value;$('ieTrainDataset').innerHTML=ieDatasets.map(d=>`<option value="${esc(d.id)}">${esc(d.id)} · ${d.counts.train.documents} 训练 / ${d.schemas.length} 槽位</option>`).join('');if(ieDatasets.some(d=>d.id===oldDataset))$('ieTrainDataset').value=oldDataset;const completed=runList.filter(r=>r.status==='completed'),old=$('ieModel').value;
    $('ieModel').innerHTML=completed.length?completed.map(r=>`<option value="${esc(r.id)}">${esc(displayName(r))}</option>`).join(''):'<option value="">等待模型训练完成</option>';
    const selected=(modelChosen?old:null)||snapshot.state.selected_run||completed.filter(r=>r.dataset==='duie2-slots-10k-v1').sort((a,b)=>(b.best_validation_relation_f1??-1)-(a.best_validation_relation_f1??-1))[0]?.id;
    if(completed.some(r=>r.id===selected))$('ieModel').value=selected;modelNote();$('ieExtract').disabled=ieInferencePending||!completed.length;
    $('ieTrainButton').disabled=runList.some(r=>['queued','running'].includes(r.status))||!['completed','not_prepared','failed'].includes(snapshot.state.phase);study();renderReport();renderAnalysis();renderErrorCategories();
    if(detailId&&(ieDetailPending||ieEvaluationPending||runList.find(r=>r.id===detailId)?.status==='running'))await showDetail(detailId);
  }catch(e){toast(e.message);}finally{busy=false;}}
  $('ieRefresh').onclick=refreshIE;refreshIE();setInterval(()=>{if(document.visibilityState==='visible'&&(snapshot?.state.phase!=='completed'||ieEvaluationPending||runList.some(r=>['queued','running'].includes(r.status))))refreshIE();},12000);
})();
