'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={population:'研究对象',intervention:'干预 / 对照',efficacy:'疗效 / 终点',adverse_event:'不良事件 / 安全性',pending:'待核验',approved:'已核验',rejected:'已驳回'};
const entityTypes={bod:'身体',dep:'科室',dis:'疾病',dru:'药物',equ:'医疗设备',ite:'医学检验',mic:'微生物',pro:'医疗程序',sym:'临床表现',other:'其他 / 不属于九类'};
let overview={},documentData=null,result=null,page=0,activeJob=null,authRequired=false,authenticated=false;
function showLogin(message=''){authenticated=false;$('appMain').hidden=true;$('loginPanel').hidden=false;$('logoutButton').hidden=true;$('loginError').textContent=message;$('loginPassword').value='';}
async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),credentials:'same-origin',cache:'no-store'});const data=await r.json();if(r.status===401&&authRequired)showLogin('登录已失效，请重新登录。');if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
async function initializeAccess(){const r=await fetch('/api/auth/session',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('无法获取登录状态。');const state=await r.json();authRequired=state.required;authenticated=!authRequired||state.authenticated;$('logoutButton').hidden=!authenticated||!authRequired;if(!authenticated){showLogin();return;}$('loginPanel').hidden=true;$('appMain').hidden=false;await refresh();}
$('loginForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('loginError').textContent='';try{const response=await fetch('/api/auth/login',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('loginUser').value,password:$('loginPassword').value})});const data=await response.json();if(!response.ok)throw Error(data.detail||'登录失败');authenticated=true;$('loginPassword').value='';$('loginPanel').hidden=true;$('appMain').hidden=false;$('logoutButton').hidden=false;await refresh();}catch(e){$('loginError').textContent=e.message;}finally{button.disabled=false;}};
$('logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{});}catch(e){toast(e.message);}finally{showLogin('已退出登录。');}};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6000);}
const phases={medical_ner_training:'医学实体模型训练中',medical_relation_training:'医学关系模型训练中',validation_selection:'验证集选择中',heldout_evaluation:'独立保留集评测中',completed:'医学模型已完成训练与评测',failed:'训练失败：查看日志'};
async function refresh(){overview=await api('/api/medical');$('phase').textContent=phases[overview.status.phase]||overview.status.phase;$('docMetric').textContent=overview.documents.length;const training=overview.relation_training;const awaitingEvaluation=training?.status==='completed'&&training.id!==overview.relation_comparison?.candidate_run?.id;if(training?.status==='running')$('relationExperiment').textContent=`${training.version==='relation-v3'?'类别求和':'类别均值'}联合关系模型正在实际训练：第 ${training.current_epoch||1} / 6 轮，${training.batches_done||0} / ${training.batches_per_epoch||'…'} 个批次。完成验证与评测前继续使用原模型。${training.resumable_epoch?'断点已保存：第 '+training.resumable_epoch+' 轮 / '+training.resumable_batches_done+' 批次。':''}`;if(awaitingEvaluation)$('relationExperiment').textContent='联合关系模型已完成六轮训练，正在等待验证与保留集对照结果。';if(training?.status==='failed')$('relationExperiment').textContent='联合关系实验失败；继续使用原模型，运行状态与原因已保留。';const comparison=overview.relation_comparison;if(comparison&&training?.status!=='running'&&!awaitingEvaluation)$('relationExperiment').textContent=`医学关系同条件对照：两阶段 ${(comparison.baseline.relation.f1*100).toFixed(2)}% → ${comparison.mean_head_control?'类别求和联合抽取':'类别均值联合抽取'} ${(comparison.candidate.relation.f1*100).toFixed(2)}%${comparison.mean_head_control?'；类别均值对照 '+(comparison.mean_head_control.relation.f1*100).toFixed(2)+'%':''}。当前使用${overview.active_relation?.version==='relation-v3'?'类别求和联合模型':overview.active_relation?.version==='relation-v2'?'类别均值联合模型':'原两阶段模型'}；为单种子、复用保留集实验。`;const d=overview.decoding_experiment;if(d)$('decoderExperiment').textContent=`独立解码对照：验证集 ${(d.selection.options[0].validation_f1*100).toFixed(2)}% → ${(d.selection.chosen.validation_f1*100).toFixed(2)}%；复用保留集 ${(d.baseline.micro.f1*100).toFixed(2)}% → ${(d.selected.micro.f1*100).toFixed(2)}%。默认保留原解码器；这不是新训练模型或独立未见测试集。`;const report=overview.report;if(report){$('nerMetric').textContent=(report.ner.micro.f1*100).toFixed(2)+'%';$('reMetric').textContent=((overview.active_relation?.metrics||report.relations).relation.f1*100).toFixed(2)+'%';$('nerScope').textContent=`${report.ner.documents} 篇保留文本 · 9 类实体`;$('reScope').textContent=`${report.relations.documents} 篇保留文本 · 53 类关系`;}
const selected=$('documentSelect').value;$('documentSelect').innerHTML=overview.documents.map(d=>`<option value="${esc(d.id)}">${esc(d.metadata.title||d.id.slice(0,8))}</option>`).join('');if(overview.documents.some(d=>d.id===selected))$('documentSelect').value=selected;$('extract').disabled=overview.status.phase!=='completed'||!overview.documents.length||!!activeJob;
if(!documentData&&overview.documents.length)await selectDocument();}
async function selectDocument(){documentData=await api('/api/medical/documents/'+$('documentSelect').value);result=null;page=0;$('documentMeta').textContent=`${documentData.text.length.toLocaleString()} 字符 · ${documentData.blocks.length} 个段落 / 表格行 · ${documentData.metadata.source}`;$('sourceText').textContent=documentData.text;$('sourceLocator').textContent='偏移对应此线性化原文，XML 保留段落 / 表格定位';$('records').innerHTML='';$('concepts').innerHTML='';$('relations').innerHTML='';$('entityRecords').innerHTML='';$('summary').textContent='文献已加载。';$('version').textContent='未选择抽取版本';$('approvedExport').hidden=$('allExport').hidden=true;$('extractionSelect').innerHTML=documentData.extractions.map(e=>`<option value="${esc(e.id)}">${esc(new Date(e.created).toLocaleString())} · ${esc(e.id.slice(0,8))}</option>`).join('');$('extractionSelect').disabled=!documentData.extractions.length;if(documentData.extractions.length)await loadResult(documentData.extractions[0].id);}
async function loadResult(id){result=await api('/api/medical/extractions/'+id);if(!Array.from($('extractionSelect').options).some(o=>o.value===id))$('extractionSelect').add(new Option(new Date(result.created_at).toLocaleString()+' · '+id.slice(0,8),id),0);$('extractionSelect').disabled=false;$('extractionSelect').value=id;$('version').textContent=`抽取 ${result.id.slice(0,8)} · ${new Date(result.created_at).toLocaleString()}`;for(const [element,mode] of [['approvedExport','approved'],['allExport','all']]){$(element).hidden=false;$(element).href=`/api/medical/extractions/${result.id}/export?mode=${mode}`;}
$('concepts').innerHTML=result.concepts.map(c=>`<span class="concept" title="${esc(c.id)}">${esc(c.canonical)} · ${esc(c.type)} · ${c.mentions.length} 次提及</span>`).join('');const entities=Object.fromEntries(result.entities.map(e=>[e.id,e]));$('relations').innerHTML=result.relations.map(r=>`<p>${esc(entities[r.subject].text)} → ${esc(r.predicate)} → ${esc(entities[r.object].text)} <small>模型候选</small></p>`).join('')||'模型未检出医学关系。';render();renderEntities();}
const contextNames={negated:'否定线索',uncertain:'不确定线索',historical:'既往线索',family:'家族经历线索',conflicting:'作用域冲突',unmarked:'未匹配到修饰',unassigned:'未分配作用域'};
function contextCard(e){const c=e.context;if(!c||(!c.modifiers?.length&&!c.blocked_modifiers?.length))return '';const reasons={unverified_disease_surface:'疾病类型或标准名待核验',nonlocal_backward_modifier:'修饰词距离过远',outcome_or_indirect_scope:'涉及疗效或间接修饰'};return `<div class="context-card"><strong>实体上下文 · 待核验</strong>${(c.modifiers||[]).map(m=>`<p>${esc(contextNames[m.category]||m.category)}：${esc(m.cue.text)} → ${esc(m.scope.text)} <small>字符 ${m.scope.start}–${m.scope.end}</small></p>`).join('')}${(c.blocked_modifiers||[]).map(m=>`<p>未采用「${esc(m.cue.text)}」：${esc(reasons[m.reason]||m.reason)}<br><small>候选范围：${esc(m.scope.text)} · 字符 ${m.scope.start}–${m.scope.end}</small></p>`).join('')}<small>仅为文本修饰线索，不证明诊断或因果；未匹配到线索也不表示肯定。</small></div>`;}
function provenanceCard(r){const p=r.provenance_context;if(!p||p.scope==='unassigned')return '';return `<p class="flag">文献来源线索：${esc({mixed_cues:'本研究与引用研究混合，需核对',cited_study_cues:'包含引用研究或试验名称，需核对',current_study_cue:'原文明确提到本研究'}[p.scope])} · ${p.cues.map(x=>esc(x.text)).join(' / ')}</p>`;}
function bindingCards(r){const bindings=r.binding_suggestions||[];if(!bindings.length)return '';return `<details class="bindings"><summary>结构化数值候选 · ${bindings.length} 条，待核验</summary><p class="muted">只按本句明确写法匹配；未知组别保留为空，候选不等于医学结论。</p>${bindings.map((b,i)=>`<div class="binding"><strong>${esc(b.endpoint)} · ${esc(b.statistic==='median'?'中位数':'原文报告值')}</strong><p>${esc(b.arm?.text||'组别未绑定')} · ${esc(b.value)} ${esc(b.unit)}${b.unit_inherited?'（单位来自并列后项）':''}</p><small>原文值：${esc(b.value_reference.text)} · 字符 ${b.value_reference.start}–${b.value_reference.end}</small><button class="secondary" data-action="suggestion" data-binding="${i}">填入核验表单</button></div>`).join('')}</details>`;}
function render(){if(!result)return;const counts=result.review_counts;$('summary').textContent=`${result.model_windows} 个模型窗口 · ${result.entities.length} 个实体提及 · ${result.concepts.length} 个本机概念 · 待核验 ${counts.pending} / 已核验 ${counts.approved} / 已驳回 ${counts.rejected}。已跳过 ${result.skipped_non_chinese_blocks.length} 个非中文段落。`;
const filtered=result.records.filter(r=>(!$('category').value||r.category===$('category').value)&&(!$('reviewStatus').value||r.status===$('reviewStatus').value));page=Math.min(page,Math.max(0,Math.ceil(filtered.length/25)-1));const rows=filtered.slice(page*25,page*25+25);
$('records').innerHTML=rows.map(r=>`<article class="record" data-record="${esc(r.id)}"><div class="record-head"><h3>${esc(names[r.category])}</h3><span class="tag">${esc(names[r.status])} · 修订 ${r.revision}</span></div><small>${esc(r.evidence.section)} · ${esc(r.evidence.kind)} · 字符 ${r.evidence.start}–${r.evidence.end}</small><div class="evidence">${esc(r.evidence.text)}</div><div class="numbers">原文统计量：${r.numbers.map(n=>esc(n.text)).join(' / ')||'未匹配到统计量'}</div><div class="flag">${r.qualifiers.negation.length?'含否定：'+r.qualifiers.negation.map(x=>esc(x.text)).join('、'):''} ${r.qualifiers.uncertainty.length?'含不确定表达':''} ${r.qualifiers.comparison.length?'含比较表达，请核对组别':''}</div>${provenanceCard(r)}${bindingCards(r)}<div class="review-fields"><label>研究组 / 对照组<input data-field="arm" value="${esc(r.arm)}" maxlength="1000"></label><label>终点 / 事件名称<input data-field="endpoint" value="${esc(r.endpoint)}" maxlength="1000"></label><label>核验后的数值与单位<input data-field="normalized_value" value="${esc(r.normalized_value)}" maxlength="1000"></label></div><label>核验说明<input data-field="note" value="${esc(r.note)}" maxlength="2000"></label><div class="actions"><button data-action="locate" class="secondary">定位原文</button><button data-action="approved">核验通过</button><button data-action="rejected" class="secondary">驳回候选</button><button data-action="history" class="secondary">修订历史</button></div><div data-history></div></article>`).join('')||'<p class="muted">没有符合筛选条件的记录。</p>';$('pageInfo').textContent=`${page+1} / ${Math.max(1,Math.ceil(filtered.length/25))} 页 · ${filtered.length} 条`;$('previous').disabled=page===0;$('next').disabled=(page+1)*25>=filtered.length;}
function locate(evidence){const chars=Array.from(documentData.text);$('sourceText').innerHTML=esc(chars.slice(0,evidence.start).join(''))+'<mark id="sourceHighlight">'+esc(chars.slice(evidence.start,evidence.end).join(''))+'</mark>'+esc(chars.slice(evidence.end).join(''));$('sourceLocator').textContent=evidence.section+' · '+evidence.locator;$('sourceHighlight').scrollIntoView({block:'center',behavior:'smooth'});}
function renderEntities(){if(!result)return;$('concepts').innerHTML=result.concepts.map(c=>`<span class="concept" title="${esc(c.id)}">${esc(c.canonical)} · ${esc(entityTypes[c.type]||c.type)} · ${c.mentions.length} 次提及</span>`).join('');const q=$('entityQuery').value.trim().toLowerCase();const rows=result.entities.filter(e=>(e.text+' '+e.canonical+' '+(entityTypes[e.type]||e.type)).toLowerCase().includes(q)).slice(0,30);$('entityRecords').innerHTML=rows.map(e=>`<article class="record" data-entity="${esc(e.id)}"><div class="record-head"><h3>${esc(e.text)} · 字符 ${e.start}–${e.end}</h3><span class="tag">${esc(names[e.status])} · 修订 ${e.revision}</span></div><small>原模型：${esc(entityTypes[e.model_type]||e.model_type)} · ${esc(e.model_canonical)} · ${esc(e.methods.join(' / '))}</small>${contextCard(e)}<div class="review-fields"><label>核验后的类型<select data-field="type">${Object.entries(entityTypes).map(([k,v])=>`<option value="${k}" ${e.type===k||(!Object.hasOwn(entityTypes,e.type)&&k==='other')?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>标准名<input data-field="canonical" value="${esc(e.canonical)}" maxlength="1000"></label><label>核验说明<input data-field="note" value="${esc(e.note)}" maxlength="2000"></label></div><div class="actions"><button data-action="locate" class="secondary">定位提及</button><button data-action="approved">核验实体</button><button data-action="rejected" class="secondary">驳回实体</button><button data-action="history" class="secondary">实体修订历史</button></div><div data-history></div></article>`).join('')||'没有匹配实体。';}
$('entityQuery').oninput=renderEntities;
$('entityRecords').onclick=async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const article=button.closest('[data-entity]'),e=result.entities.find(x=>x.id===article.dataset.entity),action=button.dataset.action;try{if(action==='locate'){const block=documentData.blocks.find(b=>b.start<=e.start&&e.end<=b.end);locate({...block,start:e.start,end:e.end});return;}if(action==='history'){const history=await api(`/api/medical/extractions/${result.id}/entities/${e.id}/history`);article.querySelector('[data-history]').textContent=history.map(h=>`修订 ${h.revision} · ${names[h.status]} · ${h.reviewer} · ${h.payload.type} / ${h.payload.canonical} · ${h.payload.note||''}`).join('\n')||'暂无修订。';return;}button.disabled=true;const body={expected_revision:e.revision,status:action,reviewer:$('reviewer').value};for(const input of article.querySelectorAll('[data-field]'))body[input.dataset.field]=input.value||null;result=await api(`/api/medical/extractions/${result.id}/entities/${e.id}/review`,body);render();renderEntities();}catch(error){toast(error.message);button.disabled=false;}};
$('documentSelect').onchange=()=>selectDocument().catch(e=>toast(e.message));$('category').onchange=$('reviewStatus').onchange=()=>{page=0;render();};$('previous').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
$('records').onclick=async event=>{const button=event.target.closest('button[data-action]');if(!button)return;const article=button.closest('[data-record]'),r=result.records.find(x=>x.id===article.dataset.record),action=button.dataset.action;try{if(action==='suggestion'){const b=r.binding_suggestions[Number(button.dataset.binding)];article.querySelector('[data-field=arm]').value=b.arm?.text||'';article.querySelector('[data-field=endpoint]').value=b.endpoint;article.querySelector('[data-field=normalized_value]').value=`${b.value} ${b.unit}`;toast('候选已填入，请结合原文检查组别、终点和数值后再核验。');return;}if(action==='locate'){locate(r.evidence);return;}if(action==='history'){const h=await api(`/api/medical/extractions/${result.id}/records/${r.id}/history`);article.querySelector('[data-history]').innerHTML=h.map(x=>`<p>修订 ${x.revision} · ${esc(names[x.status])} · ${esc(x.reviewer)} · ${esc(x.created)}<br>${esc(x.payload.arm)} / ${esc(x.payload.endpoint)} / ${esc(x.payload.normalized_value)} / ${esc(x.payload.note)}</p>`).join('')||'暂无人工修订。';return;}button.disabled=true;const body={expected_revision:r.revision,status:action,reviewer:$('reviewer').value};for(const input of article.querySelectorAll('[data-field]'))body[input.dataset.field]=input.value||null;result=await api(`/api/medical/extractions/${result.id}/records/${r.id}/review`,body);render();}catch(e){toast(e.message);button.disabled=false;}};
$('extract').onclick=async()=>{const identifier=$('documentSelect').value;$('extract').disabled=true;try{activeJob=await api(`/api/medical/documents/${identifier}/extract`,{});$('documentSelect').disabled=true;await pollJob();}catch(e){activeJob=null;$('documentSelect').disabled=false;toast(e.message);await refresh();}};
async function pollJob(){if(!activeJob)return;activeJob=await api('/api/medical/jobs/'+activeJob.id);$('jobState').textContent=activeJob.status==='running'?'正在抽取完整文档；保留全局原文偏移。':activeJob.status;if(activeJob.status==='completed'){const id=activeJob.extraction_id;activeJob=null;$('documentSelect').disabled=false;await loadResult(id);await refresh();}else if(['failed','interrupted'].includes(activeJob.status)){const message=activeJob.error;activeJob=null;$('documentSelect').disabled=false;toast(message);await refresh();}else setTimeout(()=>pollJob().catch(e=>toast(e.message)),2000);}
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;if(file.size>1500000){toast('文件不能超过 1.5 MB');return;}$('content').value=await file.text();$('format').value=file.name.toLowerCase().endsWith('.xml')?'jats':'text';};
$('importForm').onsubmit=async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const d=await api('/api/medical/documents',{content:$('content').value,format:$('format').value,title:$('title').value,source:$('source').value});await refresh();$('documentSelect').value=d.id;await selectDocument();toast('原文已保存，重复文档会复用原有记录。');}catch(e){toast(e.message);}finally{button.disabled=false;}};
$('searchForm').onsubmit=async event=>{event.preventDefault();try{const hits=await api('/api/medical/search?q='+encodeURIComponent($('searchQuery').value));$('searchResults').innerHTML=hits.map(h=>`<div class="search-result">${esc(h.text)}<br><button class="secondary" data-extraction="${esc(h.extraction_id)}" data-record="${esc(h.record_id)}">打开证据</button></div>`).join('')||'没有检索到匹配证据。';}catch(e){toast(e.message);}};
$('searchResults').onclick=async event=>{const b=event.target.closest('[data-extraction]');if(!b)return;try{const r=await api('/api/medical/extractions/'+b.dataset.extraction);$('documentSelect').value=r.document_id;await selectDocument();await loadResult(r.id);locate(r.records.find(x=>x.id===b.dataset.record).evidence);}catch(e){toast(e.message);}};
initializeAccess().catch(e=>toast(e.message));setInterval(()=>{if(authenticated&&document.visibilityState==='visible'&&(overview.status?.phase!=='completed'||(overview.relation_training&&(overview.relation_training.status==='running'||overview.relation_training.id!==overview.relation_comparison?.candidate_run?.id)&&overview.relation_training.status!=='failed')))refresh().catch(e=>toast(e.message));},10000);

$('extractionSelect').onchange=()=>{page=0;loadResult($('extractionSelect').value).catch(e=>toast(e.message));};
